docker-exim :
 image: synst/exim:latest
 container_name: docker-exim
 hostname: exim
 restart: always
 ports:
  - "25:25"
  - "465:465"
 volumes:
  - "./config/exim-smtp.conf:/etc/exim/exim.conf:ro"
  - "./log/:/var/log/exim/"
  - "./ssl/:/etc/ssl/:ro"
